---
- name: Verify AppArmor compliance across hosts
  hosts: all
  gather_facts: yes
  become: yes

  vars:
    export_dir: "/home/ansibleadmin/Documents/linux_hardening"
    collector_host: 192.168.2.111

  tasks:

    - name: Ensure export directory exists on collector
      ansible.builtin.file:
        path: "{{ export_dir }}"
        state: directory
        mode: '0755'
      delegate_to: "{{ collector_host }}"
      run_once: true

    - name: Check if AppArmor package is installed
      ansible.builtin.shell: dpkg -l | grep apparmor
      register: apparmor_pkg
      changed_when: false
      failed_when: false

    - name: Check if AppArmor is enabled in bootloader
      ansible.builtin.shell: "grep -q 'apparmor=1' /proc/cmdline && grep -q 'security=apparmor' /proc/cmdline"
      register: apparmor_boot
      changed_when: false
      failed_when: false

    - name: Get AppArmor status
      become: yes
      ansible.builtin.command: aa-status
      register: aa_status
      changed_when: false
      failed_when: false

    - name: Build compliance report (JSON object)
      ansible.builtin.set_fact:
        apparmor_report:
          inventory_id: "{{ ansible_hostname }}"
          ip_address: "{{ inventory_hostname }}"
          ensure_apparmor_installed: "{{ 'yes' if apparmor_pkg.rc == 0 else 'no' }}"
          ensure_apparmor_enabled_bootloader: "{{ 'yes' if apparmor_boot.rc == 0 else 'no' }}"
          remediation: >-
          {% if apparmor_boot.rc != 0 %}
            Edit GRUB config (/etc/default/grub) and add 'apparmor=1 security=apparmor' to GRUB_CMDLINE_LINUX, then run 'update-grub' and reboot
          {% else %}
            No action needed
          {% endif %}
          ensure_profiles_enforce_or_complain: "{{ 'yes' if 'unconfined' not in aa_status.stdout else 'no' }}"
          ensure_profiles_enforcing: "{{ 'yes' if 'profiles are in enforce mode' in aa_status.stdout else 'no' }}"

    - name: Save JSON report directly on collector
      ansible.builtin.copy:
        dest: "{{ export_dir }}/linux_harden_report_{{ inventory_hostname }}.json"
        content: "{{ apparmor_report | to_nice_json }}"
        mode: '0644'
      delegate_to: "{{ collector_host }}"

- name: Merge all collected system info JSON files on collector
  hosts: 192.168.2.111
  become: yes
  gather_facts: no

  vars:
    export_dir: "/home/ansibleadmin/Documents/linux_hardening"
    merged_file: "linux_harden_report.json"
    become_user: root     
  
  tasks:
    - name: Merge all JSON files into one
      shell: "cat {{ export_dir }}/*.json | jq -s '.' > {{ export_dir }}/{{ merged_file }}"
      args:
        executable: /bin/bash

    - name: Confirm merged file path
      debug:
        msg: "✅ All system info merged into {{ export_dir }}/{{ merged_file }}"
