---
- name: My First Play
  hosts: 192.168.2.129, 192.168.2.111

  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:
     
   
    - name: Print message
      ansible.builtin.debug:
         msg: Hello world
