---
- name: Set and lock GNOME wallpaper system-wide (Enterprise-Safe)
  hosts: all
  become: yes
  become_user: root

  vars:
    wallpaper_source: "wallpaper.png"        # Source inside AWX project
    wallpaper_dest: "/usr/share/backgrounds/company_wallpaper.png"
    dconf_dir: "/etc/dconf/db/local.d"
    dconf_file: "00-wallpaper"
    dconf_lock_dir: "/etc/dconf/db/local.d/locks"

  tasks:

    # ---------------------------------------------------
    # 0. Install required dconf tools (prevents silent failure)
    # ---------------------------------------------------
    - name: Install dconf utilities
      ansible.builtin.package:
        name:
          - dconf-cli
          - dconf-service
        state: present

    # ---------------------------------------------------
    # 1. Ensure required directories exist
    # ---------------------------------------------------
    - name: Ensure dconf config directory exists
      ansible.builtin.file:
        path: "{{ dconf_dir }}"
        state: directory
        mode: '0755'

    - name: Ensure dconf lock directory exists
      ansible.builtin.file:
        path: "{{ dconf_lock_dir }}"
        state: directory
        mode: '0755'

    # ---------------------------------------------------
    # 2. Copy wallpaper to system directory
    # ---------------------------------------------------
    - name: Copy wallpaper to system directory
      ansible.builtin.copy:
        src: "{{ wallpaper_source }}"
        dest: "{{ wallpaper_dest }}"
        owner: root
        group: root
        mode: '0644'

    # ---------------------------------------------------
    # 3. Create system-wide GNOME wallpaper config
    # ---------------------------------------------------
    - name: Create GNOME system-wide wallpaper config
      ansible.builtin.copy:
        dest: "{{ dconf_dir }}/{{ dconf_file }}"
        content: |
          [org/gnome/desktop/background]
          picture-uri='file://{{ wallpaper_dest }}'
          picture-uri-dark='file://{{ wallpaper_dest }}'
          picture-options='centered'
        owner: root
        group: root
        mode: '0644'

    # ---------------------------------------------------
    # 4. Create lockfile to prevent user overriding wallpaper
    # ---------------------------------------------------
    - name: Create GNOME wallpaper lock file
      ansible.builtin.copy:
        dest: "{{ dconf_lock_dir }}/{{ dconf_file }}"
        content: |
          /org/gnome/desktop/background/picture-uri
          /org/gnome/desktop/background/picture-uri-dark
        owner: root
        group: root
        mode: '0444'

    # ---------------------------------------------------
    # 5. Remove existing user wallpaper overrides (CRITICAL FIX)
    # ---------------------------------------------------
    - name: Reset user wallpaper override (ignore errors if user not logged in)
      ansible.builtin.shell: |
        dconf reset /org/gnome/desktop/background/picture-uri || true
        dconf reset /org/gnome/desktop/background/picture-uri-dark || true
      ignore_errors: yes

    # ---------------------------------------------------
    # 6. Apply dconf database changes
    # ---------------------------------------------------
    - name: Update dconf database
      ansible.builtin.command: dconf update

    # ---------------------------------------------------
    # 7. Reload GNOME session to apply wallpaper immediately (no logout needed)
    # ---------------------------------------------------
    - name: Reload GNOME shell for active user (safe)
      ansible.builtin.shell: |
        pgrep -u $(whoami) gnome-shell && killall -3 gnome-shell || true
      ignore_errors: yes

    # ---------------------------------------------------
    # 8. Final message
    # ---------------------------------------------------
    - name: Display completion message
      ansible.builtin.debug:
        msg: "Company wallpaper successfully deployed + locked system-wide on GNOME."

          Changes will apply automatically at next GNOME login for all users.

