---
- name: Gather system information from all hosts
  hosts: all
  gather_facts: yes
  become: yes

  vars:
    export_temp_dir: "/tmp/sysinfo_exports"
    export_filename: "system_info_{{ inventory_hostname }}.json"
    collector_host: "192.168.2.111"  # 👈 destination host where final JSON will live

  tasks:
    - name: Ensure temporary directory exists
      file:
        path: "{{ export_temp_dir }}"
        state: directory
        mode: '0755'

    - name: Gather system information
      set_fact:
        sysinfo:
          hostname: "{{ ansible_hostname }}"
          os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
          kernel: "{{ ansible_kernel }}"
          architecture: "{{ ansible_architecture }}"
          cpu: "{{ ansible_processor[1] | default('Unknown') }}"
          ram_gb: "{{ (ansible_memtotal_mb / 1024) | round(1) }}"
          storage_gb: "{{ (ansible_mounts[0].size_total / 1024 / 1024 / 1024) | round(1) }}"
          ip_address: "{{ ansible_default_ipv4.address }}"
          timestamp: "{{ lookup('pipe', 'date +%Y-%m-%dT%H:%M:%S') }}"

    - name: Save each host info JSON on collector
      copy:
        dest: "/tmp/sysinfo_exports/{{ export_filename }}"
        content: "{{ sysinfo | to_nice_json }}"
      delegate_to: "{{ collector_host }}"
      become: false


# SECOND PLAY – merge all individual files into one
    - name: Copy JSON files from all hosts to collector
      fetch:
        src: "{{ export_dir }}/system_info_{{ ansible_host }}.json"
        dest: "/tmp/collected_files/"
        flat: yes
      delegate_to: "192.168.2.111"

- name: Combine all system info into one JSON file on collector
  hosts: 192.168.2.111
  gather_facts: no
  become: yes

  vars:
    export_dir: "/tmp/collected_files"
    output_file: "/tmp/all_system_info.json"

  tasks:
    - name: Ensure jq is installed
      apt:
        name: jq
        state: present
      become: yes

    - name: Combine all JSON files into one
      shell: "jq -s '.' {{ export_dir }}/*.json > {{ output_file }}"
      args:
        executable: /bin/bash

    - name: Display combined file path
      debug:
        msg: "All system information saved to {{ output_file }} on {{ inventory_hostname }}"
