---
- name: Gather system information
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Collect system information facts
      set_fact:
        sysinfo:
          hostname: "{{ ansible_hostname }}"
          os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
          kernel: "{{ ansible_kernel }}"
          architecture: "{{ ansible_architecture }}"
          cpu: "{{ ansible_processor[1] | regex_replace('.*Intel.*', 'Intel') | regex_replace('.*AMD.*', 'AMD') }}"
          ram_gb: "{{ (ansible_memtotal_mb / 1024) | round(0) }}"
          storage_gb: "{{ (ansible_mounts[0].size_total / 1024 / 1024 / 1024) | round(0) }}"
          current_user: "{{ lookup('env', 'USER') }}"

    - name: Show system info in human-readable format
      debug:
        msg: |
          ===== System Information =====
          Hostname: {{ sysinfo.hostname }}
          OS: {{ sysinfo.os }}
          Kernel: {{ sysinfo.kernel }}
          Architecture: {{ sysinfo.architecture }}
          CPU: {{ sysinfo.cpu }}
          RAM: {{ sysinfo.ram_gb }} GB
          Storage: {{ sysinfo.storage_gb }} GB
          Current User: {{ sysinfo.current_user }}
          =================================

    # ✅ Create artifacts directory safely relative to playbook path
    - name: Ensure artifacts directory exists
      delegate_to: localhost
      run_once: true
      become: false
      ansible.builtin.file:
        path: "{{ playbook_dir }}/artifacts"
        state: directory
        mode: '0755'

    # ✅ Save JSON output in the right place
    - name: Save JSON file to artifacts directory (on controller)
      delegate_to: localhost
      become: false
      ansible.builtin.copy:
        content: "{{ sysinfo | to_nice_json }}"
        dest: "{{ playbook_dir }}/artifacts/system_info_{{ inventory_hostname }}.json"
        mode: '0644'

    - name: Save JSON to controller host (Ubuntu)
      delegate_to: localhost
      become: false
      copy:
      content: "{{ sysinfo | to_nice_json }}"
      dest: "/opt/awx_exports/system_info_{{ inventory_hostname }}.json"


    - name: Notify completion
      debug:
        msg: "✅ System info JSON exported to {{ playbook_dir }}/artifacts (accessible via AWX admin)."
