---
- name: Gather system information
  hosts: all
  gather_facts: yes
  become_user: root

  vars:
    export_timestamp: "{{ lookup('pipe', 'date +%Y-%m-%dT%H-%M-%S') }}"

  tasks:
    - name: Collect system information facts
      set_fact:
        sysinfo:
          hostname: "{{ ansible_hostname }}"
          os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
          kernel: "{{ ansible_kernel }}"
          architecture: "{{ ansible_architecture }}"
          cpu: "{{ ansible_processor[1] | regex_replace('.*Intel.*', 'Intel') | regex_replace('.*AMD.*', 'AMD') }}"
          ram_gb: "{{ (ansible_memtotal_mb / 1024) | round(0) }}"
          storage_gb: "{{ (ansible_mounts[0].size_total / 1024 / 1024 / 1024) | round(0) }}"
          current_user: "{{ lookup('env', 'USER') }}"

    # Run once on control node: collect sysinfo from all hosts via hostvars
    - name: Write combined JSON on control node
      delegate_to: localhost
      run_once: true
      copy:
        content: >-
          {{
            groups['all']
            | map('extract', hostvars, 'sysinfo')
            | list
            | to_nice_json
          }}
        dest: "./collected_sysinfo-{{ export_timestamp }}.json"
