---
- name: Gather system information
  hosts: all
  gather_facts: yes
  become: yes

  vars:
    # Add timestamp for unique filenames (e.g. 2025-10-27T12-45-32)
    export_timestamp: "{{ lookup('pipe', 'date +%Y-%m-%dT%H-%M-%S') }}"

  tasks:
    - name: Collect system information facts
      set_fact:
        sysinfo:
          hostname: "{{ ansible_hostname }}"
          os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
          kernel: "{{ ansible_kernel }}"
          architecture: "{{ ansible_architecture }}"
          cpu: "{{ ansible_processor[1] | regex_replace('.*Intel.*', 'Intel') | regex_replace('.*AMD.*', 'AMD') }}"
          ram_gb: "{{ (ansible_memtotal_mb / 1024) | round(0) }}"
          storage_gb: "{{ (ansible_mounts[0].size_total / 1024 / 1024 / 1024) | round(0) }}"
          current_user: "{{ lookup('env', 'USER') }}"

    - name: Show system info in human-readable format
      debug:
        msg: |
          ===== System Information =====
          Hostname: {{ sysinfo.hostname }}
          OS: {{ sysinfo.os }}
          Kernel: {{ sysinfo.kernel }}
          Architecture: {{ sysinfo.architecture }}
          CPU: {{ sysinfo.cpu }}
          RAM: {{ sysinfo.ram_gb }} GB
          Storage: {{ sysinfo.storage_gb }} GB
          Current User: {{ sysinfo.current_user }}
          =================================

    # ✅ Create artifacts directory safely (in AWX runtime)
    - name: Ensure artifacts directory exists
      delegate_to: localhost
      run_once: true
      ansible.builtin.file:
        path: "./artifacts"
        state: directory
        mode: '0755'

    # ✅ Save JSON file in AWX job’s artifacts directory
    - name: Save JSON output inside AWX artifacts
      delegate_to: localhost
      ansible.builtin.copy:
        content: "{{ sysinfo | to_nice_json }}"
        dest: "./artifacts/system_info_{{ inventory_hostname }}_{{ export_timestamp }}.json"
        mode: '0644'

    - name: Notify completion
      debug:
        msg: |
          ✅ System info JSON exported to './artifacts' folder
          → Download it from AWX UI under **Job → Artifacts**
