---
# ===========================
# PLAY 1 – Gather system info
# ===========================
- name: Gather system information from all hosts
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    collector_host: "192.168.2.111"        # Host where final merged file will be stored
    remote_export_dir: "/tmp/sysinfo_exports"  # Directory on each remote host
    collector_export_dir: "/tmp/collected_sysinfo"  # Directory on collector host

  tasks:
    - name: Ensure export directory exists on each host
      file:
        path: "{{ remote_export_dir }}"
        state: directory
        mode: "0755"

    - name: Gather system information
      set_fact:
        sysinfo:
          hostname: "{{ ansible_hostname }}"
          ip_address: "{{ ansible_host }}"
          os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
          kernel: "{{ ansible_kernel }}"
          architecture: "{{ ansible_architecture }}"
          cpu: "{{ ansible_processor[0] | default('Unknown CPU') }}"
          ram_gb: "{{ (ansible_memtotal_mb / 1024) | round(1) }}"
          storage_gb: "{{ (ansible_mounts[0].size_total / 1024 / 1024 / 1024) | round(1) }}"
          timestamp: "{{ ansible_date_time.iso8601 }}"

    - name: Write system info JSON file on each host
      copy:
        content: "{{ sysinfo | to_nice_json }}"
        dest: "{{ remote_export_dir }}/system_info_{{ ansible_host }}.json"

# ===============================================
# PLAY 2 – Copy and combine all JSONs on collector
# ===============================================
- name: Collect and merge system info
  hosts: all
  gather_facts: no

  vars:
    collector_host: "192.168.2.111"
    remote_export_dir: "/tmp/sysinfo_exports"
    collector_export_dir: "/tmp/collected_sysinfo"

  tasks:
    - name: Ensure collector directory exists
      file:
        path: "{{ collector_export_dir }}"
        state: directory
        mode: "0755"
      delegate_to: "{{ collector_host }}"
      run_once: true

    - name: Copy JSON files from each host to collector
      fetch:
        src: "{{ remote_export_dir }}/system_info_{{ ansible_host }}.json"
        dest: "{{ collector_export_dir }}/"
        flat: yes
      delegate_to: "{{ collector_host }}"

    - name: Merge all JSONs into a single file
      delegate_to: "{{ collector_host }}"
      run_once: true
      shell: |
        jq -s '.' {{ collector_export_dir }}/*.json > {{ collector_export_dir }}/all_system_info.json
      args:
        executable: /bin/bash

    - name: Display merged file path
      debug:
        msg: "✅ Combined JSON saved at {{ collector_export_dir }}/all_system_info.json on {{ collector_host }}"
