---
- name: Gather system information
  hosts: all
  gather_facts: yes   # This automatically runs the setup module
  become: yes
  become_user: root

  tasks:
    - name: Show current logged-in user
      ansible.builtin.command: whoami
      register: current_user

    - name: Display system information
      ansible.builtin.debug:
        msg: |
          ===== System Information =====
          Hostname: {{ ansible_hostname }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Kernel: {{ ansible_kernel }}
          Architecture: {{ ansible_architecture }}
          CPU Model: {{ ansible_processor[1] }}
          Total RAM: {{ ansible_memtotal_mb }} MB
          Storage (root fs): {{ ansible_mounts[0].size_total | human_readable }}
          Current User: {{ current_user.stdout }}
          System Vendor: {{ ansible_system_vendor }}
          Product Name: {{ ansible_product_name }}
          =================================
    - name: Export system info as JSON artifact
      ansible.builtin.set_stats:
        data:
          system_report: "{{ system_info | to_nice_json }}"
