---
- name: Gather system information from all hosts
  hosts: all
  gather_facts: yes
  become: yes

  vars:
    export_temp_dir: "/tmp/sysinfo_exports"
    export_filename: "system_info_{{ inventory_hostname }}.json"
    collector_host: "192.168.2.200"  # 👈 destination host where final JSON will live

  tasks:
    - name: Ensure temporary directory exists
      file:
        path: "{{ export_temp_dir }}"
        state: directory
        mode: '0755'

    - name: Gather system information
      set_fact:
        sysinfo:
          hostname: "{{ ansible_hostname }}"
          os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
          kernel: "{{ ansible_kernel }}"
          architecture: "{{ ansible_architecture }}"
          cpu: "{{ ansible_processor[1] | default('Unknown') }}"
          ram_gb: "{{ (ansible_memtotal_mb / 1024) | round(1) }}"
          storage_gb: "{{ (ansible_mounts[0].size_total / 1024 / 1024 / 1024) | round(1) }}"
          ip_address: "{{ ansible_default_ipv4.address }}"
          timestamp: "{{ lookup('pipe', 'date +%Y-%m-%dT%H:%M:%S') }}"

    - name: Save each host info JSON on collector
      copy:
        dest: "/tmp/sysinfo_exports/{{ export_filename }}"
        content: "{{ sysinfo | to_nice_json }}"
      delegate_to: "{{ collector_host }}"
      become: false


# SECOND PLAY – merge all individual files into one
- name: Combine all host system info into one JSON file
  hosts: 192.168.2.200   # 👈 collector host IP
  gather_facts: no
  become: yes

  vars:
    export_temp_dir: "/tmp/sysinfo_exports"
    final_export_file: "/mnt/shared/all_system_info.json"

  tasks:
    - name: Ensure destination directory exists
      file:
        path: "{{ export_temp_dir }}"
        state: directory

    - name: Combine all JSON files into one single array
      shell: |
        jq -s '.' {{ export_temp_dir }}/*.json > {{ final_export_file }}
      args:
        executable: /bin/bash

    - name: Show combined file location
      debug:
        msg: "✅ All system info saved to {{ final_export_file }}"
