---
- name: Gather system information
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Show system info in human-readable format
      ansible.builtin.debug:
        msg: |
          ===== System Information =====
          Hostname: {{ ansible_hostname }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Kernel: {{ ansible_kernel }}
          Architecture: {{ ansible_architecture }}
          CPU: {{ ansible_processor[1] | regex_replace('.*Intel.*', 'Intel') | regex_replace('.*AMD.*', 'AMD') }}
          RAM: {{ (ansible_memtotal_mb / 1024) | round(0) }} GB
          Storage: {{ (ansible_mounts[0].size_total / 1024 / 1024 / 1024) | round(0) }} GB
          Current User: {{ lookup('env', 'USER') }}
          =================================
