---
- name: Gather system information from all hosts
  hosts: all
  gather_facts: yes
  become: yes

  vars:
    export_temp_dir: "/tmp/sysinfo_exports"
    export_filename: "system_info_{{ inventory_hostname }}.json"

  tasks:
    - name: Ensure temporary directory exists
      file:
        path: "{{ export_temp_dir }}"
        state: directory
        mode: '0755'

    - name: Gather system information
      set_fact:
        sysinfo:
          hostname: "{{ ansible_hostname }}"
          os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
          kernel: "{{ ansible_kernel }}"
          architecture: "{{ ansible_architecture }}"
          cpu: "{{ ansible_processor[1] | default('Unknown') }}"
          ram_gb: "{{ (ansible_memtotal_mb / 1024) | round(1) }}"
          storage_gb: "{{ (ansible_mounts[0].size_total / 1024 / 1024 / 1024) | round(1) }}"
          ip_address: "{{ ansible_default_ipv4.address }}"
          timestamp: "{{ lookup('pipe', 'date +%Y-%m-%dT%H:%M:%S') }}"

    - name: Save each host info to controller temp folder
      copy:
        dest: "/tmp/sysinfo_exports/{{ export_filename }}"
        content: "{{ sysinfo | to_nice_json }}"
      delegate_to: 192.168.2.111   # 👈 your collector/destination host IP
      run_once: false


- name: Combine all JSONs into one file on the collector host
  hosts: 192.168.2.111      # 👈 same collector host IP
  become: yes
  gather_facts: no

  vars:
    export_temp_dir: "/tmp/sysinfo_exports"
    final_export_file: "/mnt/shared/all_system_info.json"

  tasks:
    - name: Ensure export directory exists
      file:
        path: "{{ export_temp_dir }}"
        state: directory

    - name: Combine all JSON files into one
      shell: |
        jq -s '.' {{ export_temp_dir }}/*.json > {{ final_export_file }}
      args:
        executable: /bin/bash

    - name: Show final export path
      debug:
        msg: "✅ All system info combined and saved to {{ final_export_file }}"
