---
- name: Gather detailed hardware and system information
  hosts: all
  gather_facts: yes
  become: yes

  vars:
    export_dir: "/tmp/sysinfo_exports"
    export_filename: "system_info_{{ inventory_hostname }}.json"
    collector_host: 192.168.2.111

  tasks:
    - name: Ensure export directory exists on collector
      file:
        path: "{{ export_dir }}"
        state: directory
        mode: '0755'
      delegate_to: "{{ collector_host }}"
      run_once: true

    # ---------- CPU INFO ----------
    - name: Get full CPU model name
      shell: "dmidecode -t processor | grep 'Version:' | head -1 | awk -F': ' '{print $2}'"
      register: cpu_model
      ignore_errors: yes

    # ---------- MEMORY INFO ----------
    - name: Get total number of memory slots
      shell: "dmidecode -t memory | grep -c 'Locator:'"
      register: total_slots
      ignore_errors: yes

    - name: Get installed RAM modules
      shell: >
        dmidecode -t memory |
        awk '/Locator:/ {slot=$2} /Size:/ {size=$2" "$3; if (size != "No Module Installed") print slot"="size}'
      register: used_slots
      ignore_errors: yes

    # ---------- STORAGE INFO ----------
    - name: Get disk details (model, size, type)
      shell: >
        lsblk -d -o NAME,MODEL,ROTA,SIZE |
        awk 'NR>1 {type=($3==0)?"SSD":"HDD"; print $1"="type", " $2", " $4}'
      register: disk_info
      ignore_errors: yes

    # ---------- BASIC SYSTEM INFO ----------
    - name: Gather basic system info
      set_fact:
        sysinfo:
          hostname: "{{ ansible_hostname }}"
          os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
          kernel: "{{ ansible_kernel }}"
          architecture: "{{ ansible_architecture }}"
          ip_address: "{{ ansible_default_ipv4.address | default('N/A') }}"
          cpu_model: "{{ cpu_model.stdout | default('Unknown') }}"
          ram_total_gb: "{{ (ansible_memtotal_mb / 1024) | round(1) }}"
          total_ram_slots: "{{ total_slots.stdout | default('Unknown') }}"
          used_ram_slots: "{{ used_slots.stdout_lines | default([]) }}"
          disks: "{{ disk_info.stdout_lines | default([]) }}"
          timestamp: "{{ lookup('pipe', 'date +%Y-%m-%dT%H:%M:%S') }}"

    # ---------- EXPORT JSON TO COLLECTOR ----------
    - name: Copy JSON data to collector
      copy:
        dest: "{{ export_dir }}/{{ export_filename }}"
        content: "{{ sysinfo | to_nice_json }}"
      delegate_to: "{{ collector_host }}"

    - name: Confirm export path
      debug:
        msg: "✅ System info for {{ inventory_hostname }} saved to {{ export_dir }}/{{ export_filename }} on {{ collector_host }}"

# ---------------- SECOND PLAY ----------------
- name: Merge all collected system info JSON files on collector
  hosts: 192.168.2.111
  become_user: root
  gather_facts: no

  vars:
    export_dir: "/tmp/sysinfo_exports"
    merged_file: "sys_info.json"

  tasks:
    - name: Merge all JSON files into one
      shell: "cat {{ export_dir }}/*.json | jq -s '.' > {{ export_dir }}/{{ merged_file }}"
      args:
        executable: /bin/bash

    - name: Confirm merged file path
      debug:
        msg: "✅ All system info merged into {{ export_dir }}/{{ merged_file }}"
