---
- name: Upgrade Google Chrome
  hosts: all
  become_user: root
  gather_facts: no

  tasks:
    - name: Run apt only-upgrade for Chrome
      ansible.builtin.command: apt --only-upgrade install -y google-chrome-stable
