---
- name: Upgrade Google Chrome
  hosts: all
  become: yes
  become_user: root
  gather_facts: no

  tasks:
    - name: Show current Chrome version
      ansible.builtin.command: google-chrome --version
      register: chrome_before
      ignore_errors: yes

    - name: Display current version
      ansible.builtin.debug:
        msg: "Current Chrome version: {{ chrome_before.stdout | default('Not Installed') }}"

    - name: Run apt only-upgrade for Chrome
      ansible.builtin.command: apt-get update --fix-missing && apt --only-upgrade install -y google-chrome-stable
      register: chrome_upgrade
      ignore_errors: yes

    - name: Show updated Chrome version
      ansible.builtin.command: google-chrome --version
      register: chrome_after
      ignore_errors: yes

    - name: Display updated version
      ansible.builtin.debug:
        msg: |
          ✅ Chrome version upgrade complete:
          Before: {{ chrome_before.stdout | default('Not Installed') }}
          After:  {{ chrome_after.stdout | default('Unknown') }}
