---
- name: Check and Upgrade Google Chrome
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    # 🧩 Step 1: Get current version
    - name: Get current version of Google Chrome (before upgrade)
      ansible.builtin.command: google-chrome --version
      register: chrome_before
      ignore_errors: yes

    - name: Show current version
      ansible.builtin.debug:
        msg: "Current Chrome version: {{ chrome_before.stdout | default('Not Installed') }}"

    # ⚙️ Step 2: Upgrade Chrome using your exact command
    - name: Run apt only-upgrade for Chrome
      ansible.builtin.command: apt --only-upgrade install -y google-chrome-stable
      register: chrome_upgrade
      changed_when: "'upgraded' in chrome_upgrade.stdout or chrome_upgrade.rc == 0"
      failed_when: chrome_upgrade.rc != 0

    - name: Show upgrade result
      ansible.builtin.debug:
        msg: "Chrome upgrade output: {{ chrome_upgrade.stdout | default('No output') }}"

    # 🔄 Step 3: Get new version
    - name: Get new version of Google Chrome (after upgrade)
      ansible.builtin.command: google-chrome --version
      register: chrome_after
      ignore_errors: yes

    - name: Show updated Chrome version
      ansible.builtin.debug:
        msg: |
          ✅ Chrome version updated successfully!
          Before: {{ chrome_before.stdout | default('Not Installed') }}
          After:  {{ chrome_after.stdout | default('Unknown') }}
