---
- name: Upgrade Google Chrome
  hosts: all
  become: yes
  become_user: root
  gather_facts: no

  tasks:
    - name: Show current Chrome version
      ansible.builtin.command: google-chrome --version
      register: chrome_before
      ignore_errors: yes

    - name: Display current version
      ansible.builtin.debug:
        msg: "Current Chrome version: {{ chrome_before.stdout | default('Not Installed') }}"

    # ✅ Option 2: Proper Ansible way to update and upgrade Chrome
    - name: Update package lists
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade Chrome only
      ansible.builtin.apt:
        name: google-chrome-stable
        state: latest
        only_upgrade: yes

    - name: Show updated Chrome version
      ansible.builtin.command: google-chrome --version
      register: chrome_after
      ignore_errors: yes

    - name: Display updated version
      ansible.builtin.debug:
        msg: |
          ✅ Chrome version upgrade complete:
          Before: {{ chrome_before.stdout | default('Not Installed') }}
          After:  {{ chrome_after.stdout | default('Unknown') }}
